

import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import javazoom.jl.player.Player;
import java.io.FileInputStream;
import java.io.BufferedInputStream;
import java.io.File;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.imageio.ImageIO;
import javax.smartcardio.Card;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * frmPrincipal.java
 *
 * Created on 07/03/2012, 21:56:42
 */

/**
 *
 * @author Johnnylee Bryan Marques da Rocha
 */
public class frmPrincipal extends javax.swing.JFrame {
    ExecutorService executor = Executors.newFixedThreadPool(1);
    Musica musica = new Musica();
    SFX sfx = new SFX();

    public void habilitaJogador(boolean jogador){
        if (jogador){
            btBicudaP1.setEnabled(true);
            btMaozadaP1.setEnabled(true);
            btBufeteP1.setEnabled(true);
            btRodoP1.setEnabled(true);
            btDefesaP1.setEnabled(true);
            btHadukenP1.setEnabled(true);
            btBicudaP2.setEnabled(false);
            btMaozadaP2.setEnabled(false);
            btBufeteP2.setEnabled(false);
            btRodoP2.setEnabled(false);
            btDefesaP2.setEnabled(false);
            btHadukenP2.setEnabled(false);
        }
        else{
            btBicudaP1.setEnabled(false);
            btMaozadaP1.setEnabled(false);
            btBufeteP1.setEnabled(false);
            btRodoP1.setEnabled(false);
            btDefesaP1.setEnabled(false);
            btHadukenP1.setEnabled(false);
            btBicudaP2.setEnabled(true);
            btMaozadaP2.setEnabled(true);
            btBufeteP2.setEnabled(true);
            btRodoP2.setEnabled(true);
            btDefesaP2.setEnabled(true);
            btHadukenP2.setEnabled(true);
        }

    }
    /** Creates new form frmPrincipal */
    public frmPrincipal() {
        initComponents();
        JOptionPane.showMessageDialog(null,"Fight");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btBufeteP1 = new javax.swing.JButton();
        btMaozadaP1 = new javax.swing.JButton();
        btBicudaP1 = new javax.swing.JButton();
        btRodoP1 = new javax.swing.JButton();
        btDefesaP1 = new javax.swing.JButton();
        btHadukenP1 = new javax.swing.JButton();
        lblVidaP1 = new javax.swing.JLabel();
        lblForcaP1 = new javax.swing.JLabel();
        vidaP1 = new javax.swing.JProgressBar();
        forcaP1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lblJogador1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btBufeteP2 = new javax.swing.JButton();
        btMaozadaP2 = new javax.swing.JButton();
        btBicudaP2 = new javax.swing.JButton();
        btRodoP2 = new javax.swing.JButton();
        btDefesaP2 = new javax.swing.JButton();
        btHadukenP2 = new javax.swing.JButton();
        lblVidaP2 = new javax.swing.JLabel();
        lblForcaP2 = new javax.swing.JLabel();
        vidaP2 = new javax.swing.JProgressBar();
        forcaP2 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        btIniciar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btNomes = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btImagemP1 = new javax.swing.JButton();
        btImagemP2 = new javax.swing.JButton();
        btMúsica = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BECO FIGHT");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("VIDA:");

        jLabel4.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("FORÇA:");

        btBufeteP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btBufeteP1.setText("BUFETE");
        btBufeteP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBufeteP1ActionPerformed(evt);
            }
        });

        btMaozadaP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btMaozadaP1.setText("MAOZADA");
        btMaozadaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaozadaP1ActionPerformed(evt);
            }
        });

        btBicudaP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btBicudaP1.setText("BICUDA");
        btBicudaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBicudaP1ActionPerformed(evt);
            }
        });

        btRodoP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btRodoP1.setText("RODO");
        btRodoP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRodoP1ActionPerformed(evt);
            }
        });

        btDefesaP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btDefesaP1.setText("DEFESA");
        btDefesaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDefesaP1ActionPerformed(evt);
            }
        });

        btHadukenP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btHadukenP1.setText("HADUKEN");
        btHadukenP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHadukenP1ActionPerformed(evt);
            }
        });

        lblVidaP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        lblVidaP1.setForeground(new java.awt.Color(102, 102, 102));
        lblVidaP1.setText("100");

        lblForcaP1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        lblForcaP1.setForeground(new java.awt.Color(102, 102, 102));
        lblForcaP1.setText("30");

        vidaP1.setForeground(new java.awt.Color(0, 204, 0));
        vidaP1.setValue(100);

        forcaP1.setForeground(new java.awt.Color(255, 0, 0));
        forcaP1.setMaximum(30);
        forcaP1.setValue(30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clique Imagem Para Adicionar uma Foto");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));

        lblJogador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJogador1.setForeground(new java.awt.Color(153, 153, 153));
        lblJogador1.setText("Jogador 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblVidaP1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblForcaP1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forcaP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidaP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBufeteP1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btBicudaP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDefesaP1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btRodoP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHadukenP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMaozadaP1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJogador1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {forcaP1, vidaP1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblJogador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblVidaP1))
                    .addComponent(vidaP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblForcaP1))
                    .addComponent(forcaP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btBufeteP1)
                    .addComponent(btMaozadaP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBicudaP1)
                    .addComponent(btRodoP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btDefesaP1)
                    .addComponent(btHadukenP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("VIDA:");

        jLabel6.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("FORÇA:");

        btBufeteP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btBufeteP2.setText("BUFETE");
        btBufeteP2.setEnabled(false);
        btBufeteP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBufeteP2ActionPerformed(evt);
            }
        });

        btMaozadaP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btMaozadaP2.setText("MAOZADA");
        btMaozadaP2.setEnabled(false);
        btMaozadaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaozadaP2ActionPerformed(evt);
            }
        });

        btBicudaP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btBicudaP2.setText("BICUDA");
        btBicudaP2.setEnabled(false);
        btBicudaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBicudaP2ActionPerformed(evt);
            }
        });

        btRodoP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btRodoP2.setText("RODO");
        btRodoP2.setEnabled(false);
        btRodoP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRodoP2ActionPerformed(evt);
            }
        });

        btDefesaP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btDefesaP2.setText("DEFESA");
        btDefesaP2.setEnabled(false);
        btDefesaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDefesaP2ActionPerformed(evt);
            }
        });

        btHadukenP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        btHadukenP2.setText("HADUKEN");
        btHadukenP2.setEnabled(false);
        btHadukenP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHadukenP2ActionPerformed(evt);
            }
        });

        lblVidaP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        lblVidaP2.setForeground(new java.awt.Color(102, 102, 102));
        lblVidaP2.setText("100");

        lblForcaP2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 18));
        lblForcaP2.setForeground(new java.awt.Color(102, 102, 102));
        lblForcaP2.setText("30");

        vidaP2.setForeground(new java.awt.Color(0, 204, 0));
        vidaP2.setValue(100);

        forcaP2.setForeground(new java.awt.Color(255, 0, 0));
        forcaP2.setMaximum(30);
        forcaP2.setValue(30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clique Imagem Para Adicionar uma Foto");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));

        lblJogador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJogador2.setForeground(new java.awt.Color(153, 153, 153));
        lblJogador2.setText("Jogador 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVidaP2)
                            .addComponent(lblForcaP2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vidaP2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forcaP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btDefesaP2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btHadukenP2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btBicudaP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBufeteP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btMaozadaP2)
                                .addComponent(btRodoP2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJogador2))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btBicudaP2, btBufeteP2, btDefesaP2, btHadukenP2, btMaozadaP2, btRodoP2});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {forcaP2, vidaP2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblJogador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblVidaP2))
                    .addComponent(vidaP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lblForcaP2))
                    .addComponent(forcaP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBufeteP2)
                    .addComponent(btMaozadaP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBicudaP2)
                    .addComponent(btRodoP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDefesaP2)
                    .addComponent(btHadukenP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        btIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/joystick.jpg"))); // NOI18N
        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair.jpg"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btNomes.setText("Nomes");
        btNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNomesActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 48));
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Beco Fight Final");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btImagemP1.setText("Imagem P1");
        btImagemP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImagemP1ActionPerformed(evt);
            }
        });

        btImagemP2.setText("Imagem P2");
        btImagemP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImagemP2ActionPerformed(evt);
            }
        });

        btMúsica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musica.jpg"))); // NOI18N
        btMúsica.setText("Música");
        btMúsica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMúsicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNomes)
                        .addGap(18, 18, 18)
                        .addComponent(btImagemP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImagemP2)
                        .addGap(18, 18, 18)
                        .addComponent(btMúsica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btSair)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIniciar)
                    .addComponent(btNomes)
                    .addComponent(btImagemP1)
                    .addComponent(btImagemP2)
                    .addComponent(btSair)
                    .addComponent(btMúsica))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btBufeteP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBufeteP1ActionPerformed
        // TODO add your handling code here:

        if(p1.darbufete(p2)){
        lblForcaP1.setText(String.valueOf(p1.getForca()));
        forcaP1.setValue(p1.getForca());
        sfx.executaSoco();

        if (p2.getHp()<0){
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
        }
        if (p2.Verificajogo()){
           lblVidaP2.setText(String.valueOf(p2.getHp()));
           vidaP2.setValue(p2.getHp());
           habilitaJogador(false);
        }
        else{
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador1.getText()+" venceu");

        }
        }
    }//GEN-LAST:event_btBufeteP1ActionPerformed

    private void btBufeteP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBufeteP2ActionPerformed
        // TODO add your handling code here:
        if(p2.darbufete(p1)){
        lblForcaP2.setText(String.valueOf(p2.getForca()));
        forcaP2.setValue(p2.getForca());
        sfx.executaSoco();
        if (p1.getHp()<0){
            lblVidaP1.setText("0");
            vidaP1.setValue(0);

        }
        if (p1.Verificajogo()){
           lblVidaP1.setText(String.valueOf(p1.getHp()));
           vidaP1.setValue(p1.getHp());
           habilitaJogador(true);
        }
        else{
           lblVidaP1.setText("0");
           vidaP1.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador2.getText()+" venceu");
        }
        }
    }//GEN-LAST:event_btBufeteP2ActionPerformed

    private void btMaozadaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaozadaP1ActionPerformed
        // TODO add your handling code here:
        if(p1.darmaozada(p2)){
        lblForcaP1.setText(String.valueOf(p1.getForca()));
        forcaP1.setValue(p1.getForca());
        sfx.executaSoco();
        if (p2.getHp()<0){
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
        }
        if (p2.Verificajogo()){
           lblVidaP2.setText(String.valueOf(p2.getHp()));
           vidaP2.setValue(p2.getHp());
           habilitaJogador(false);
        }
        else{
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador1.getText()+" venceu");
        }
        }
    }//GEN-LAST:event_btMaozadaP1ActionPerformed

    private void btMaozadaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaozadaP2ActionPerformed
        // TODO add your handling code here:
        if(p2.darmaozada(p1)){
        lblForcaP2.setText(String.valueOf(p2.getForca()));
        forcaP2.setValue(p2.getForca());
        sfx.executaSoco();
        if (p1.getHp()<0){
            lblVidaP1.setText("0");
            vidaP1.setValue(0);
        }
        if (p1.Verificajogo()){
           lblVidaP1.setText(String.valueOf(p1.getHp()));
           vidaP1.setValue(p1.getHp());
           habilitaJogador(true);
        }
        else{
           lblVidaP1.setText("0");
           vidaP1.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador2.getText()+" venceu");
        }
        }
    }//GEN-LAST:event_btMaozadaP2ActionPerformed

    private void btBicudaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBicudaP1ActionPerformed
        // TODO add your handling code here:
         if(p1.darbicuda(p2)){
        lblForcaP1.setText(String.valueOf(p1.getForca()));
        forcaP1.setValue(p1.getForca());
        sfx.executaSoco();
        if (p2.getHp()<0){
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
        }
        if (p2.Verificajogo()){
           lblVidaP2.setText(String.valueOf(p2.getHp()));
           vidaP2.setValue(p2.getHp());
           habilitaJogador(false);
        }
        else{
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador1.getText() + " venceu");
        }
        }
    }//GEN-LAST:event_btBicudaP1ActionPerformed

    private void btRodoP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRodoP1ActionPerformed
        // TODO add your handling code here:
         if(p1.darrodo(p2)){
        lblForcaP1.setText(String.valueOf(p1.getForca()));
        forcaP1.setValue(p1.getForca());
        sfx.executaSoco();
        if (p2.getHp()<0){
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
        }
        if (p2.Verificajogo()){
           lblVidaP2.setText(String.valueOf(p2.getHp()));
           vidaP2.setValue(p2.getHp());
           habilitaJogador(false);

        }
        else{
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador1.getText()+" venceu");
        }
        }
    }//GEN-LAST:event_btRodoP1ActionPerformed

    private void btDefesaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDefesaP1ActionPerformed
        // TODO add your handling code here:
        p1.defesa();
        habilitaJogador(false);
        lblForcaP1.setText(String.valueOf(p1.getForca()));
        forcaP1.setValue(p1.getForca());
    }//GEN-LAST:event_btDefesaP1ActionPerformed

    private void btHadukenP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHadukenP1ActionPerformed
        // TODO add your handling code here:
         if(p1.darhaduken(p2)){
        lblForcaP1.setText(String.valueOf(p1.getForca()));
        forcaP1.setValue(p1.getForca());
        try{
            FileInputStream arquivo = new FileInputStream("C:/Beco Fight/mp3/HADOUKEN.mp3");
            BufferedInputStream mp3 = new BufferedInputStream(arquivo);
            Player tocar = new Player(mp3);
            tocar.play();
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        }
        if (p2.getHp()<0){
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
        }
        if (p2.Verificajogo()){
           lblVidaP2.setText(String.valueOf(p2.getHp()));
           vidaP2.setValue(p2.getHp());
           habilitaJogador(false);
        }
        else{
            lblVidaP2.setText("0");
            vidaP2.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador1.getText()+" venceu");
        }
        }
    }//GEN-LAST:event_btHadukenP1ActionPerformed

    private void btBicudaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBicudaP2ActionPerformed
        // TODO add your handling code here:
        if(p2.darbicuda(p1)){
        lblForcaP2.setText(String.valueOf(p2.getForca()));
        forcaP2.setValue(p2.getForca());
        sfx.executaSoco();
        if (p1.getHp()<0){
            lblVidaP1.setText("0");
            vidaP1.setValue(0);
        }
        if (p1.Verificajogo()){
           lblVidaP1.setText(String.valueOf(p1.getHp()));
           vidaP1.setValue(p1.getHp());
           habilitaJogador(true);
        }
        else{
           lblVidaP1.setText("0");
           vidaP1.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador2.getText() + " venceu");
        }
        }
    }//GEN-LAST:event_btBicudaP2ActionPerformed

    private void btRodoP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRodoP2ActionPerformed
        // TODO add your handling code here:
        if(p2.darrodo(p1)){
        lblForcaP2.setText(String.valueOf(p2.getForca()));
        forcaP2.setValue(p2.getForca());
        sfx.executaSoco();
        if (p1.getHp()<0){
            lblVidaP1.setText("0");
            vidaP1.setValue(0);
        }
        if (p1.Verificajogo()){
           lblVidaP1.setText(String.valueOf(p1.getHp()));
           vidaP1.setValue(p1.getHp());
           habilitaJogador(true);
        }
        else{
           lblVidaP1.setText("0");
           vidaP1.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador2.getText()+" venceu");
        }
        }
    }//GEN-LAST:event_btRodoP2ActionPerformed

    private void btDefesaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDefesaP2ActionPerformed
        // TODO add your handling code here:
        p2.defesa();
        habilitaJogador(true);
        lblForcaP2.setText(String.valueOf(p2.getForca()));
        forcaP2.setValue(p2.getForca());
    }//GEN-LAST:event_btDefesaP2ActionPerformed

    private void btHadukenP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHadukenP2ActionPerformed
        // TODO add your handling code here:
        if(p2.darhaduken(p1)){
        lblForcaP2.setText(String.valueOf(p2.getForca()));
        forcaP2.setValue(p2.getForca());
        try{
            FileInputStream arquivo = new FileInputStream("C:/Beco Fight/mp3/HADOUKEN.mp3");
            BufferedInputStream mp3 = new BufferedInputStream(arquivo);
            Player tocar = new Player(mp3);
            tocar.play();
        }
        catch(Exception e){

        }
        if (p1.getHp()<0){
            lblVidaP1.setText("0");
            vidaP1.setValue(0);
        }
        if (p1.Verificajogo()){
           lblVidaP1.setText(String.valueOf(p1.getHp()));
           vidaP1.setValue(p1.getHp());
           habilitaJogador(true);
        }
        else{
           lblVidaP1.setText("0");
           vidaP1.setValue(0);
            JOptionPane.showMessageDialog(null,lblJogador1.getText() + " venceu");
        }
        }
    }//GEN-LAST:event_btHadukenP2ActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        // TODO add your handling code here:
        p1.novoJogo();
        p2.novoJogo();
        lblVidaP1.setText("100");
        lblVidaP2.setText("100");
        lblForcaP1.setText("30");
        lblForcaP2.setText("30");
        vidaP1.setValue(100);
        vidaP2.setValue(100);
        forcaP1.setValue(30);
        forcaP2.setValue(30);
        habilitaJogador(true);
        JOptionPane.showMessageDialog(null,"Fight");
    }//GEN-LAST:event_btIniciarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNomesActionPerformed

        p1.escolherNome();
            lblJogador1.setText(p1.getNome().toString());
        p2.escolherNome();
            lblJogador2.setText(p2.getNome().toString());

    }//GEN-LAST:event_btNomesActionPerformed

    private void btImagemP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImagemP1ActionPerformed

   try{
       JFileChooser chooser = new JFileChooser();
       FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");

       chooser.setFileFilter(filter);
       chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            int res = chooser.showOpenDialog(null);
             if(res == JFileChooser.APPROVE_OPTION){
              File diretorio = chooser.getSelectedFile();
              BufferedImage bi = ImageIO.read(diretorio);
              BufferedImage aux2 = new BufferedImage(100,100, bi.getType());
              Graphics2D g = aux2.createGraphics();
              AffineTransform at = AffineTransform.getScaleInstance((double)100/bi.getWidth(), (double)100/bi.getHeight());
              g.drawRenderedImage(bi, at);

              ImageIcon img = new ImageIcon(aux2);

        JOptionPane.showMessageDialog(null, "Você escolheu o diretório: " + diretorio.getAbsolutePath());

        jLabel1.setText("");
        jLabel1.setIcon(img);


    }
    else{
        JOptionPane.showMessageDialog(null, "Nenhuma imagem selecionada. ");
    }
   }
   catch(Exception e){
       e.printStackTrace();

   }

    }//GEN-LAST:event_btImagemP1ActionPerformed

    private void btImagemP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImagemP2ActionPerformed
      try{
       JFileChooser chooser = new JFileChooser();
       FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");

       chooser.setFileFilter(filter);
       chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            int res = chooser.showOpenDialog(null);
             if(res == JFileChooser.APPROVE_OPTION){
              File diretorio = chooser.getSelectedFile();
              BufferedImage bi = ImageIO.read(diretorio);
              BufferedImage aux2 = new BufferedImage(100,100, bi.getType());
              Graphics2D g = aux2.createGraphics();
              AffineTransform at = AffineTransform.getScaleInstance((double)100/bi.getWidth(), (double)100/bi.getHeight());
              g.drawRenderedImage(bi, at);

              ImageIcon img = new ImageIcon(aux2);

        JOptionPane.showMessageDialog(null, "Você escolheu o diretório: " + diretorio.getAbsolutePath());

        jLabel2.setText("");
        jLabel2.setIcon(img);

    }
    else{
        JOptionPane.showMessageDialog(null, "Nenhuma imagem selecionada. ");
    }
   }
   catch(Exception e){
       e.printStackTrace();

   }
    }//GEN-LAST:event_btImagemP2ActionPerformed

    private void btMúsicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMúsicaActionPerformed
             executor.execute(musica);
    }//GEN-LAST:event_btMúsicaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBicudaP1;
    private javax.swing.JButton btBicudaP2;
    private javax.swing.JButton btBufeteP1;
    private javax.swing.JButton btBufeteP2;
    private javax.swing.JButton btDefesaP1;
    private javax.swing.JButton btDefesaP2;
    private javax.swing.JButton btHadukenP1;
    private javax.swing.JButton btHadukenP2;
    private javax.swing.JButton btImagemP1;
    private javax.swing.JButton btImagemP2;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btMaozadaP1;
    private javax.swing.JButton btMaozadaP2;
    private javax.swing.JButton btMúsica;
    private javax.swing.JButton btNomes;
    private javax.swing.JButton btRodoP1;
    private javax.swing.JButton btRodoP2;
    private javax.swing.JButton btSair;
    private javax.swing.JProgressBar forcaP1;
    private javax.swing.JProgressBar forcaP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblForcaP1;
    private javax.swing.JLabel lblForcaP2;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblVidaP1;
    private javax.swing.JLabel lblVidaP2;
    private javax.swing.JProgressBar vidaP1;
    private javax.swing.JProgressBar vidaP2;
    // End of variables declaration//GEN-END:variables
    Jogador p1 = new Jogador("Jogador 1", 100, 30);
    Jogador p2 = new Jogador("Jogador 2", 100, 30);

}